apiVersion: v2
name: aiecommerce
description: AI-Powered E-Commerce Analytics Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ecommerce
  - machine-learning
  - microservices
  - ai
  - csharp
  - dotnet
home: https://github.com/yourusername/aiecommerce-platform
sources:
  - https://github.com/yourusername/aiecommerce-platform
maintainers:
  - name: Your Name
    email: your.email@example.com
    url: https://github.com/yourusername
icon: https://raw.githubusercontent.com/yourusername/aiecommerce-platform/main/docs/logo.png

dependencies:
  - name: postgresql
    version: 12.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: 11.9.1
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 7.0.19
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: kibana
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: kibana.enabled
  - name: logstash
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: logstash.enabled
  - name: jaeger
    version: 0.69.0
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled
